name: code_talks_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  sqflite: ^2.0.3+1
  intl: ^0.17.0
  icons_launcher: ^2.0.4
  flutter_slidable: ^2.0.0
  fluttertoast: ^8.0.9

  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

icons_launcher:
  image_path: 'assets/list.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true